apiVersion: batch/v1
kind: CronJob
metadata:
  name: cmdb-ingest
  namespace: cmdb
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:8.8.0
            args: ["-X","POST","http://api.cmdb.svc.cluster.local/ingest/run"]
          restartPolicy: OnFailure
