apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.nginxServiceName }}
            port:
              number: {{ .Values.nginxServicePort }}
