apiVersion: apps/v1
kind: Deployment
metadata:
  name: { include "chart.name" . }
  labels:
    {- include "common.labels" . | nindent 4 }
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: { include "chart.name" . }
  template:
    metadata:
      labels:
        app: { include "chart.name" . }
    spec:
      containers:
      - name: extsys2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports: [{{ containerPort: 8002 }}]
---
apiVersion: v1
kind: Service
metadata:
  name: { include "chart.name" . }
spec:
  type: { .Values.service.type }
  selector:
    app: { include "chart.name" . }
  ports:
  - port: { .Values.service.port }
    targetPort: { .Values.service.targetPort }
    protocol: TCP
    name: http
